version: 2.1

# Uso del Orb de Python para simplificar la configuración.
orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    # Utiliza un executor preconfigurado del Orb de Python.
    executor: python/default  # Usa la versión por defecto del Orb

    steps:
      - checkout  # Clona el repositorio
      - python/install-packages:  # Instala las dependencias con pip
          pkg-manager: pip
          pip-dependency-file: requirements.txt  # Asegúrate de que este archivo existe
      - run:
          name: Ejecutar Pruebas
          command: pytest  # Ejecuta pytest para las pruebas

workflows:
  version: 2
  test_workflow:
    jobs:
      - build-and-test
