version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.12  # Usa Python 3.12 como imagen base
    steps:
      - checkout  # Clona tu repositorio
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Instala pytest y otras dependencias
      - run:
          name: Establecer PYTHONPATH
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)  # Añade la raíz del proyecto al PYTHONPATH
      - run:
          name: Ejecutar pruebas con pytest
          command: pytest  # Ejecuta pytest para descubrir y ejecutar las pruebas

workflows:
  version: 2
  test_workflow:
    jobs:
      - build-and-test
