# Indica que estamos usando la versión 2.1 del motor de CircleCI
version: 2.1

# Usando un orb de Python para simplificar el proceso de configuración
orbs:
  python: circleci/python@1.2.3  # Puedes verificar la versión más reciente en la documentación de CircleCI

# Definición del trabajo principal
jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Imagen Docker con Python 3.8
    steps:
      - checkout  # Clona el código desde tu repositorio
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requisitos.txt  # Instala las dependencias
      - run:
          name: Ejecutar pruebas
          command: |
            python principal.py  # Cambia esto si tienes un script específico de pruebas
            # O utiliza pytest si tus pruebas están estructuradas así: pytest

# Definición del flujo de trabajo
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
