# Usa la versión 2.1 del motor de CircleCI
version: 2.1

# Importando el orb oficial de Python de CircleCI
orbs:
  python: circleci/python@2.1.1  # Asegúrate de que esta versión esté disponible

# Definición del trabajo de construcción y prueba
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12  # Imagen oficial de Python 3.12
    steps:
      - checkout  # Clona el repositorio
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requisitos.txt  # Asegúrate de tener este archivo en el proyecto
      - run:
          name: Ejecutar pruebas
          command: |
            pytest  # Ejecuta pytest para las pruebas

# Definición del flujo de trabajo (workflow)
workflows:
  sample:
    jobs:
      - build-and-test
